name: chandravanshi_mahasabha_app
description: "अखिल भारतवर्षीय चंद्रवंशी क्षत्रिय महासभा आधिकारिक मोबाइल ऐप्लिकेशन"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
